name: mix_stack
description: MixStack lets you connects Flutter smoothly with Native pages, supports things like Multiple Tab Embeded Flutter View, Dynamic tab changing, and more. You can enjoy a smooth transition from legacy native code to Flutter with it.
version: 1.0.2
homepage: https://github.com/yuewen/mix_stack

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.yuewen.mix_stack
        pluginClass: MixStackPlugin
      ios:
        pluginClass: MixStackPlugin